spring.application.name=test
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/my_db
spring.datasource.username=postgres
spring.datasource.password=5555
spring.jpa.hibernate.ddl-auto=update