spring.application.name=test
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/my_db
spring.datasource.username=post
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update